### ISSUE TITLE
Shows tasks compilation errors, when it's not

### ISSUE THREAD

**Issue by haposik** [Kotlin/kotlin-koans#148]
Every time i press 'Check Task' it shows me, that I've got compilation error, even though answer.kt and Task.kt are identical
<img width="1492" alt="image" src="https://user-images.githubusercontent.com/34166320/39399798-25fce84c-4b2d-11e8-9f4d-5f1337507e5c.png">
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/34166320/39399803-33b478b0-4b2d-11e8-95c4-3691933dca8b.png">

**Comment by svtk** [comment]
I've added the issue in our tracker here: https://youtrack.jetbrains.com/issue/EDU-1500.
Please add the details (there): which version of IntelliJ Idea / Android Studio you're using, which version of Edu plugin you're using, which actions lead to this error (you just join the course, then click 'check task', right?).
I'm closing the issue so that the following discussion was in youtrack, where the Edu team can monitor it.
